apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-local-pv
  labels:
    {{- range $key, $value := .Values.wordpress.persistence.selector.matchLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  storageClassName: {{.Values.wordpress.persistence.storageClass}}
  accessModes:
    - {{.Values.wordpress.persistence.accessMode}}
  capacity:
    storage: {{.Values.wordpress.persistence.size}}
  local:
    path: {{.Values.wordpress.persistence.path}}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              {{- with .Values.wordpress.persistence.hostNames}}
                {{- range . }}
                - {{ . }}
                {{- end }}
              {{- end }}