apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "wordpresslocal.fullname" .) }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
    - hosts:
        - {{.Values.ingress.hosts.wp.host}}
      secretName: tls-secret-wp
  rules:
    - host: {{.Values.ingress.hosts.wp.host}}
      http:
        paths:
          - path: {{.Values.ingress.hosts.wp.host}}
            pathType: {{ .Values.ingress.hosts.wp.pathType }}
            backend:
              service:
                name: wordpress
                port:
                  number: {{ .Values.wordpress.service.ports.http }}