apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
# When you use stringData, then it is encoded automatically by k8s
stringData:
  api-token: {{ .Values.cloudflare.auth.apiToken | quote }}