ingress:
  enabled: false
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: 0m
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
  hosts:
    wp:
      host: chart-example.local
      path: /
      pathType: ImplementationSpecific

wordpress:
  fullnameOverride: wordpress
  persistence:
    storageClass: local-storage
    selector:
      matchLabels:
        app: wordpress
    path: /mnt/extra/wordpress/wpdata
    hostNames:
      - node-de
  mariadb:
    fullnameOverride: mariadb
    primary:
      persistence:
        storageClass: local-storage
        selector:
          matchLabels:
            app: mariadb
        path: /mnt/extra/wordpress/mariadb
        hostNames:
          - node-de
cloudflare:
  auth:
    apiToken: your-cloudflare-api-token